#!/usr/bin/env bash
# Bash script that redirects to another page
apt-get -y update
apt-get -y install nginx
sudo sed -i "42i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
